"""empty message

Revision ID: aaa98160cd59
Revises: 54357aeca082
Create Date: 2020-04-13 01:50:35.143637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa98160cd59'
down_revision = '54357aeca082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('join_date', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'join_date')
    # ### end Alembic commands ###
